### PR TITLE
Add Django 2.0 alpha to tests

### PR DESCRIPTION
**Pull request by orf**

### CODE REVIEW

**Comment by hggh** [comment]
the unit tests fails for 2.0. because of the missing import of urlresolvers.

**Comment by fxfitz** [comment]
@orf Do you have any plans on trying to get this merged? I'm looking to use this package in my Django 2.0 project.

Thanks!

**Comment by orf** [comment]
Sorry, I guess I completely forgot. I'll see if I can work on it tonight,
else anyone else can branch off mine and submit a working PR if they feel
like it :+1:

**Comment by fxfitz** [comment]
No worries! I figured I would wait a few days so you can get the contribution credit :-)

If I don't see anything over the next few days, I'll take a whack at it.

**Pull request closed without merging**
