### PR TITLE
Bug fix for prefetch_related returning empty results on querysets

### PR DESCRIPTION
**Pull request by jmacul2**
A current bug exists when you do:

`qs = Model.objects.all().prefetch_related('relation')`

...on models that have MacAddressField and _NetAddressField as primary keys.  The merge on prefetching doesn't happen producing empty results.  IE:

`qs[0].relation.all()`

...produces and empty queryset.  

But if you call the same query without prefretch_related, it will produce results.  

This pull request fixes this issue to the best of my knowledge.

### CODE REVIEW

**Comment by jmacul2** [comment]
I see this is failing in Travis....I'll look into that.

**Comment by jmacul2** [comment]
So after looking at this for a few days, I don't believe that the current implementation of how ArrayField is setup will allow this to work without breaking prefetch_related.

In order to get prefetch_related to work, "get_db_prep_value" needs to pass prepared=False.  My understanding is thats how it knows whether to treat the value as a string or and Inet/Macaddr.  But ArrayField is abstracted to use prepared=False already to create a list of values (array) for Postgres to use.  

The only solution I can think of is to use an abstracted ArrayField for MacAddressField and _NetAddressField

Any help here would be appreciated.

**Comment by jmacul2** [comment]
I really think this is a hack, but it passed the tests.

**Comment by jimfunk** [comment]
I'm OK with this :-)

Thanks.

**Pull request merged**
